### PR TITLE
Update project.clj

### PR DESCRIPTION
**Pull request by rcarmo**
Update to latest New Relic version

### CODE REVIEW

**Comment by rcarmo** [comment]
Great! any idea when this will be pushed to clojars? :)

**Comment by MichaelBlume** [comment]
Done =)

I'm curious, though, was this actually slowing you down? Because you can always do

```
:dependencies [[com.climate/clj-newrelic "0.2.0" :exclusions [com.newrelic.agent.java/newrelic-api]]
                         [com.newrelic.agent.java/newrelic-api "3.13.0"]]
```

**Comment by rcarmo** [comment]
Hmmm. I hadn't come across that kind of override yet. Very nice, just learned a new Leiningen trick. Thanks!

**Comment by MichaelBlume** [comment]
No problem =)

**Pull request merged**
